fix: COM-2385 Поправил смещеный к правому краю адрес на мобильных
CSSSR/csssr.com pull request #1470
Opened 2020-08-19 11:05 UTC by vkosinov

## Задача
- ссылка на jira: COM-2385
- стенд: http://fix-com-2385.csssr.cloud/

## Чек-лист
- [x] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-08-20 07:40 UTC, ArtyomResh requested changes

2020-08-20 07:40 UTC, ArtyomResh commented on components/contact-us/ContactUs/Map/Address/Address.styles.js
> +      transition: height 100ms ease-in-out;
Добавь тогда overflow:hidden, что бы текст не вылезал за блок, пока играет анимация

2020-08-20 07:57 UTC, vkosinov commented on components/contact-us/ContactUs/Map/Address/Address.styles.js
> +      transition: height 100ms ease-in-out;
http://s.csssr.ru/UJ4QCUXM4/2020-08-20-10-57-00.jpg - Может тогда лучше просто убрать анимацию ?

2020-08-20 07:58 UTC, vkosinov commented on components/contact-us/ContactUs/Map/Address/Address.styles.js
> +      transition: height 100ms ease-in-out;
С учетом того что сверху у нас анимация справа на лево то сверху вниз по моему лучше убрать

2020-08-20 08:26 UTC, vkosinov commented on components/contact-us/ContactUs/Map/Address/Address.styles.js
> +      transition: height 100ms ease-in-out;
Удалил анимацию

2020-08-25 07:03 UTC, Yankovsky approved these changes

2020-08-25 07:05 UTC, merged