[fix: COM-2435] Truncated mobile close button size
CSSSR/csssr.com pull request #1478
Opened 2020-08-20 15:54 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2435
- стенд: http://fix-com-2435.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-08-20 16:40 UTC, Yankovsky approved these changes

2020-08-31 07:45 UTC, ArtyomResh commented
@BenuelBertran Надо [коммит подписать](https://github.com/CSSSR/csssr.com/files/5148995/DT-17631083-120220-1425-2.pdf) и направить в релизную ветку.

2020-08-31 12:02 UTC, Yankovsky commented
https://confluence.csssr.io/pages/viewpage.action?pageId=17631083

2020-09-01 08:05 UTC, ArtyomResh requested changes
[У задачи есть релиз](http://s.csssr.ru/U31J879TR/20200901110502.jpg). Нужно создать релизную ветку и направить ПР в неё.

2020-09-01 16:08 UTC, BenuelBertran commented
> https://confluence.csssr.io/pages/viewpage.action?pageId=17631083

Нет доступа (login\pass не верны)

2020-09-02 07:30 UTC, ArtyomResh approved these changes

2020-09-08 09:09 UTC, merged