[feat: COM-2513] Error pages with Layout
CSSSR/csssr.com pull request #1487
Opened 2020-08-24 11:07 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2513
- стенд: http://feat-com-2513.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-08-26 15:28 UTC, ArtyomResh requested changes
[Нужно оставить только хедер](https://csssr.slack.com/archives/C0165LH3ZB7/p1598454493066100?thread_ts=1598443282.045100&cid=C0165LH3ZB7)

2020-08-26 15:28 UTC, ArtyomResh commented on package.json
> +    "@csssr/csssr-shared-header": "1.0.86",
Это кажется лишнее, тут ведь ещё пока не используется csssr-shared-header, а старый лежит, так?

2020-08-26 15:28 UTC, ArtyomResh commented
Направьте этот PR в какую-нибудь препродовую ветку, не надо сразу в мастер

2020-09-02 07:56 UTC, ArtyomResh requested changes
Тут просто 500 ошибка и белый экран при переходе на страницу ошибок

2020-09-07 14:27 UTC, BenuelBertran commented
> [Нужно оставить только хедер]
Убрал футер

2020-09-07 14:28 UTC, BenuelBertran commented
> Направьте этот PR в какую-нибудь препродовую ветку, не надо сразу в мастер

Поменял ветку на релизную для задач по новому хедеру

2020-09-07 14:29 UTC, BenuelBertran commented
> Тут просто 500 ошибка и белый экран при переходе на страницу ошибок

Возможно, был сбой на серверах. Сейчас всё открывается и работает, можно смотреть

2020-09-08 07:57 UTC, ArtyomResh requested changes
Всё ещё [пятисотит](http://s.csssr.ru/U31J879TR/20200908105440.jpg). [На локальном хосте тоже](http://s.csssr.ru/U31J879TR/20200908105457.jpg). Вот лог из терминала: 
```
Warning: Failed prop type: Link: unknown props found: data-testid
    in Link
    in SharedHeader
    in Fragment
    in Context.Consumer
    in Context.Consumer
    in Styled(SharedHeader) (at Error404Page.jsx:96)
    in Fragment
    in Error404Page
    in Fragment
    in Context.Consumer
    in Context.Provider
    in BasicProvider
    in Context.Consumer
    in Styled(Error404Page) (at msBrowserProvider.js:10)
    in Context.Consumer (at msBrowserProvider.js:9)
    in Context.Consumer (at msBrowserProvider.js:7)
    in Unknown (at l10nProvider.js:7)
    in Context.Consumer (at l10nProvider.js:7)
    in Wrapper
    in withRouter(Wrapper) (at 404.js:6)
    in Custom404 (at _app.js:215)
    in Context.Provider (at pagesListProvider.js:12)
    in PagesListProvider (at _app.js:212)
    in Context.Provider
    in Context.Consumer
    in ThemeProvider (at _app.js:211)
    in Context.Provider (at deviceProvider.js:12)
    in DeviceProvider (at _app.js:210)
    in Context.Provider (at msBrowserProvider.js:19)
    in Context.Provider (at msBrowserProvider.js:18)
    in MsBrowserProvider (at _app.js:209)
    in Context.Provider (at l10nProvider.js:16)
    in L10nProvider (at _app.js:208)
    in Context.Provider (at _app.js:207)
    in Fragment
    in MyApp
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
Warning: Failed prop type: The prop `href` is marked as required in `Link`, but its value is `undefined`.
    in Link
    in GenericLink
    in DesktopLinkWrapper
    in li
    in MainNavItem
    in Fragment
    in Context.Consumer
    in Context.Consumer
    in Styled(MainNavItem)
    in ul
    in MainNav
    in MainNav
    in Fragment
    in Context.Consumer
    in Context.Consumer
    in Styled(Component)
    in div
    in div
    in nav
    in Navigation
    in Fragment
    in Context.Consumer
    in Context.Consumer
    in Styled(Navigation)
    in header
    in Context.Provider
    in Context.Consumer
    in ThemeProvider
    in Context.Provider
    in Context.Provider
    in SharedHeader
    in Fragment
    in Context.Consumer
    in Context.Consumer
    in Styled(SharedHeader) (at Error404Page.jsx:96)
    in Fragment
    in Error404Page
    in Fragment
    in Context.Consumer
    in Context.Provider
    in BasicProvider
    in Context.Consumer
    in Styled(Error404Page) (at msBrowserProvider.js:10)
    in Context.Consumer (at msBrowserProvider.js:9)
    in Context.Consumer (at msBrowserProvider.js:7)
    in Unknown (at l10nProvider.js:7)
    in Context.Consumer (at l10nProvider.js:7)
    in Wrapper
    in withRouter(Wrapper) (at 404.js:6)
    in Custom404 (at _app.js:215)
    in Context.Provider (at pagesListProvider.js:12)
    in PagesListProvider (at _app.js:212)
    in Context.Provider
    in Context.Consumer
    in ThemeProvider (at _app.js:211)
    in Context.Provider (at deviceProvider.js:12)
    in DeviceProvider (at _app.js:210)
    in Context.Provider (at msBrowserProvider.js:19)
    in Context.Provider (at msBrowserProvider.js:18)
    in MsBrowserProvider (at _app.js:209)
    in Context.Provider (at l10nProvider.js:16)
    in L10nProvider (at _app.js:208)
    in Context.Provider (at _app.js:207)
    in Fragment
    in MyApp
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
TypeError: Cannot read property 'indexOf' of undefined
    at addBasePath (webpack-internal:///./node_modules/next/dist/next-server/lib/router/router.js:32:15)
    at eval (webpack-internal:///./node_modules/next/dist/client/link.js:111:40)
    at Link.eval [as formatUrls] (webpack-internal:///./node_modules/next/dist/client/link.js:35:20)
    at Link.render (webpack-internal:///./node_modules/next/dist/client/link.js:235:14)
    at processChild (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/render.js:3:298)
    at Object.renderPage (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/render.js:46:1020)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:133:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:50:85)
    at loadGetInitialProps (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/render.js:46:1330)
    at async /Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:68:285
    at async /Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:67:142
    at async DevServer.renderToHTMLWithComponents (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:91:254)
    at async DevServer.renderErrorToHTML (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:93:321)
    at async DevServer.renderErrorToHTML (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/server/next-dev-server.js:22:1145)
    at async DevServer.render (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:48:236)
    at async Object.fn (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/next-server.js:35:852)
locale detector: en was found in path, it was parsed as language part of full locale, en-us was found in cookie, it is in whitelist, so locale was set to en-us
TypeError: Cannot read property 'indexOf' of undefined
    at addBasePath (webpack-internal:///./node_modules/next/dist/next-server/lib/router/router.js:32:15)
    at eval (webpack-internal:///./node_modules/next/dist/client/link.js:111:40)
    at Link.eval [as formatUrls] (webpack-internal:///./node_modules/next/dist/client/link.js:35:20)
    at Link.render (webpack-internal:///./node_modules/next/dist/client/link.js:235:14)
    at processChild (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/artem/Documents/work.nosync/csssr.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/render.js:3:298)
    at Object.renderPage (/Users/artem/Documents/work.nosync/csssr.com/node_modules/next/dist/next-server/server/render.js:46:1020)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_ [...]

2020-11-10 09:22 UTC, ArtyomResh commented
Задача на холде, возможно никогда не будет реализована

2020-11-10 09:22 UTC, closed without merging