feat(lazy-content): [COM-2015]
CSSSR/csssr.com pull request #1509
Opened 2020-08-27 06:09 UTC by Paqura

## Задача
- ссылка на jira: COM-2015
- стенд: http://feat-com-2015.csssr.cloud/

### Релиз
* https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* стенд: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud

## Чек-лист
- [ ] PR в ветку релиза
- [x ] Указаны ревьюеры
- [x ] Стенды собрались и работают
- [x ] Код работает полностью согласно описанию задачи
- [x ] eslint и dev-консоль браузера без ошибок

## Дополнительно
* документация по добавленным библиотекам
* скриншоты

2020-08-27 07:47 UTC, Paqura commented
В принципе, в этой задаче сделана сразу и https://jira.csssr.io/browse/COM-2036

2020-08-27 07:52 UTC, ArtyomResh requested changes
Классный хук 👍 

Давай только не будем сразу мержить в master. У вас есть какой-нибудь релиз для этой задачки и других фиксов? Можем направить эту и подобные ей задачки в него?

2020-08-27 07:52 UTC, ArtyomResh commented on hooks/useLazy.js
> +            target.setAttribute('src', dataSrc)
Возникает вопрос, почему одно и тоже действие написано разными способами. В этом есть какой-то смысл или это просто непоследовательность? Давай тут так же на 17 строчке запишем или наоборот – на 17 как тут.

2020-08-27 07:52 UTC, ArtyomResh commented on hooks/useLazy.js
> +export const useLazy = ({ className }) => {
Давай сразу добавим атрибут options, который мы будем передавать в observer, на случай, если мы заходим поменять `rootMargin` или `treshhold` у `IntersectionObserver`

2020-08-27 08:07 UTC, Paqura commented on hooks/useLazy.js
> +            target.setAttribute('src', dataSrc)
Да, тут скорей непоследовательность: я решил объединить две задачи и совсем забыл подрефачить.
Сделаю как на 17.

2020-08-27 08:08 UTC, Paqura commented on hooks/useLazy.js
> +export const useLazy = ({ className }) => {
Ок

2020-08-27 08:09 UTC, Paqura commented
> Классный хук 👍
> 
> Давай только не будем сразу мержить в master. У вас есть какой-нибудь релиз для этой задачки и других фиксов? Можем направить эту и подобные ей задачки в него?

У нас эти задачки просто появились на доске, я честно говоря не очень в курсе флоу.

2020-08-27 09:15 UTC, Yankovsky requested changes

2020-08-27 09:15 UTC, Yankovsky commented on pages/_app.js
> +                    <LazyLoader className="lazy" />
Странное решение вот так вот инициировать ленивую загрузку.
Может быть лучше сделать компоненты-обёртки над ресурсами/компонентами, которые хотим лениво загружать?
API посмотреть можно в готовых либах https://github.com/loktar00/react-lazy-load https://github.com/twobin/react-lazyload

В принципе, если они не очень большие, можно их подключить к нам.

2020-08-28 08:32 UTC, Paqura commented on pages/_app.js
> +                    <LazyLoader className="lazy" />
@Yankovsky посмотри, пожалуйста, на последнее решение. Если норм - то норм, если нет, то можно добавить библиотеку.

2020-09-03 08:47 UTC, Yankovsky commented on pages/_app.js
> +                    <LazyLoader className="lazy" />
Стало лучше, но остался document.querySelector вне скоупа компонента и вообще почему поиск элементов через классы?
Давай добавим эту библиотеку https://github.com/twobin/react-lazyload

2020-09-07 07:28 UTC, Paqura commented
перенёс изменения сюда, т.к. решение совсем другое:
https://github.com/CSSSR/csssr.com/pull/1561
@Yankovsky @ArtyomResh

2020-09-30 09:05 UTC, closed without merging