fix(requests): COM-2079 vacancies error handling
CSSSR/csssr.com pull request #1514
Opened 2020-08-27 13:44 UTC by ArtyomResh

- add error handler for MainPage and JobsPage vacancies request

## Задача
- ссылка на jira: COM-2079

## Чек-лист
- [ ] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-08-27 13:45 UTC, ArtyomResh commented
В генерации sitemap и тестах обработку делать не стал, думаю там должны стрелять ошибки

2020-08-27 14:38 UTC, Yankovsky requested changes

2020-08-27 14:38 UTC, Yankovsky commented on components/main/MainPage.jsx
> +      Sentry.withScope(() => {
Я бы в catch выставлял vacancies = []

2020-08-31 07:54 UTC, ArtyomResh commented on components/main/MainPage.jsx
> +      Sentry.withScope(() => {
Ок, ща поменяю

2020-08-31 12:04 UTC, Yankovsky approved these changes

2020-09-02 15:16 UTC, merged