feat(lazy-load): [COM-2015]
CSSSR/csssr.com pull request #1561
Opened 2020-09-07 07:26 UTC by Paqura

## Задача
- ссылка на jira: COM-2015
- стенд: http://feat-com-2015-lazy-load.csssr.cloud/

### Релиз
* https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* стенд: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud

## Чек-лист
- [ ] PR в ветку релиза
- [ ] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [ ] Код работает полностью согласно описанию задачи
- [ ] eslint и dev-консоль браузера без ошибок

## Дополнительно
* документация по добавленным библиотекам
* скриншоты

2020-09-07 08:25 UTC, Yankovsky approved these changes

2020-09-08 07:51 UTC, ArtyomResh requested changes

2020-09-08 07:51 UTC, ArtyomResh commented on components/Footer/Footer.jsx
> +            </LazyLoad>
[Видео подгружается но не проигрывается](http://s.csssr.ru/U31J879TR/20200908104801.mp4) или [же совсем не подгружается](http://s.csssr.ru/U31J879TR/20200908104801.mp4)

2020-09-08 12:16 UTC, Paqura commented on components/Footer/Footer.jsx
> +            </LazyLoad>
обновил стили

2020-09-10 07:28 UTC, ArtyomResh approved these changes

2020-09-30 08:49 UTC, Yankovsky approved these changes

2020-09-30 08:50 UTC, merged