fix: COM-2690 Remove checkbox from candidate form
CSSSR/csssr.com pull request #1590
Opened 2020-09-14 14:30 UTC by dyurein

## Задача
- ссылка на jira: https://jira.csssr.io/browse/COM-2690
- стенд: http://fix-com-2690.csssr.cloud/

2020-09-15 08:52 UTC, ArtyomResh requested changes

2020-09-15 08:52 UTC, ArtyomResh commented on components/job/CandidateInfoSection/CandidateInfoSection.styles.js
> +  && {
Кажется один & лишний

2020-09-15 08:52 UTC, ArtyomResh commented on components/job/JobPage.jsx
> +            initialValues={{ ...initialValues, privacyPolicy: true }}
Вот это забыл подчистить :)

2020-09-15 10:18 UTC, dyurein commented on components/job/CandidateInfoSection/CandidateInfoSection.styles.js
> +  && {
Тут тоже для увеличения специфичности, перебить стили

2020-09-16 08:56 UTC, ArtyomResh approved these changes

2020-09-18 10:09 UTC, dyurein commented
Без спреда initial values форма что-то не отправляется, со спредом `filteredValues.privacyPolicy = true` уже не нужна

2020-09-21 13:58 UTC, ArtyomResh approved these changes

2020-09-28 09:52 UTC, merged