Feat/com 2722
CSSSR/csssr.com pull request #1614
Opened 2020-09-23 08:28 UTC by dyurein

## Задача
- ссылка на jira: https://jira.csssr.io/browse/COM-2722
- стенд: http://feat-com-2722.com.csssr.cloud/

2020-09-23 16:15 UTC, ArtyomResh requested changes

2020-09-23 16:15 UTC, ArtyomResh commented on components/OurCases/DevCases/Case/Case.jsx
> +      : 'right'
Тут можно проще если `index` без остатка делится на 2 то это `left`, если с остатком, то `right`

2020-09-23 16:15 UTC, ArtyomResh commented on components/OurCases/DevCases/Case/Case.styles.js
> +    &:not(:nth-of-type(1)):not(:nth-of-type(2)) {
Это стили для элемента начиная со второго, так? Тогда можно упростить до nth-of-type(n + 2)

2020-09-24 08:56 UTC, dyurein commented on components/OurCases/DevCases/Case/Case.styles.js
> +    &:not(:nth-of-type(1)):not(:nth-of-type(2)) {
Для всех кроме первого и второго

2020-09-24 14:16 UTC, ArtyomResh approved these changes

2020-09-24 14:44 UTC, merged