feat(ab-tests): COM-2795 remove old ab-tests data
CSSSR/csssr.com pull request #1658
Opened 2020-10-07 11:54 UTC by ArtyomResh

## Дополнительно
Я не стал удалять код для ab тестов полностью, думаю велика вероятность что мы ещё будем запускать какие-нибудь ab тесты в будущем. Я удалил код и файлы связанные с прошедшими ab тестами и добавил проверку на наличие тестов и куки для них.

2020-10-07 12:14 UTC, Yankovsky approved these changes

2020-10-08 10:17 UTC, Yankovsky commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
Давай просто папку вернём.

2020-10-08 11:56 UTC, ArtyomResh commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
Это не работает. Когда я попробовал вернуть папку, гит не увидел никаких изменений, нечего было комментить. Я папку и не удалял, только файлы из неё, похоже, что при коммите пустые папки удаляются из дифа.

2020-10-08 12:03 UTC, ArtyomResh commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F

2020-10-08 13:43 UTC, Yankovsky commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
Было бы здорово, чтобы директория сохранялась, может быть тащить из неё файлы только с расширением json и оставить какой-нибудь ридми или json.example.

Может быть не удалять ab тесты, а ставить им дату до которой они работают.

Хорошо иметь примеры и чтобы директория была на месте.

Можно сейчас не делать.

2020-10-08 14:34 UTC, ArtyomResh commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
Добавлю ридми в следующей задаче по тестам 👌

2020-10-08 14:37 UTC, ArtyomResh commented on server/ab/middleware.js
> +  if (fs.existsSync(experimentsDirPath)) {
Хотя, могу и тут :)

2020-10-08 15:09 UTC, Yankovsky requested changes

2020-10-08 15:09 UTC, Yankovsky commented on server/ab/experiments/README.md
> +    "optimizeExperimentId": "ASdkvSRW42uaWI_A12eASd"
Это же невалидный json

2020-10-08 15:14 UTC, Yankovsky requested changes

2020-10-08 15:14 UTC, Yankovsky commented on components/Head.jsx
> +          <meta name="twitter:image" content={props.ogImage.url} />
Ага, пропустили баг

2020-10-08 15:14 UTC, Yankovsky commented on server/ab/middleware.js
> +    const experimentsFileNames = fs.readdirSync(experimentsDirPath)
Вот сюда теперь попадёт README файл

2020-10-09 11:50 UTC, Yankovsky commented on server/ab/experiments/README.md
> +    "optimizeExperimentId": "ASdkvSRW42uaWI_A12eASd"
Запятую надо вернуть

2020-10-09 11:51 UTC, Yankovsky approved these changes

2020-10-09 15:21 UTC, Yankovsky commented
Запятую в доку надо вернуть

2020-10-13 12:40 UTC, merged