feat: COM-2038 Lazy load images
CSSSR/csssr.com pull request #1664
Opened 2020-10-09 15:36 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2038
- стенд: http://feat-com-2038.com.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [+] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [+] Код работает полностью согласно описанию задачи
- [ ] eslint и dev-консоль браузера без ошибок

2020-10-09 16:05 UTC, Yankovsky approved these changes

2020-10-12 07:07 UTC, ArtyomResh commented
@BenuelBertran тебе нужно [подписать коммиты](https://confluence.csssr.io/pages/viewpage.action?pageId=17631083), без этого не получится ничего из твоего запушить в репу. После подписи коммиты в этом PR надо будет ребейзнуть.

2020-10-13 13:12 UTC, ArtyomResh approved these changes

2020-11-10 12:16 UTC, ArtyomResh requested changes
Не на всех изображения стоит loading="lazy". Я читал что лучше не ставить этот атрибут на первые изображения на странице, но у нас уже на некторых стоит стоит, так что давай пока для простоты поставим его везде и проверим как это будет работать, потом если что уберём

2020-11-10 12:25 UTC, ArtyomResh commented
Фикс не работал, потому что аттрибут loading в csssr.images ты добавил, но версию пакета никто не поднял и не опубликовал, и на com осталась старая версия без аттрибута loading и поэтому ничего не работало. Не забывай свои фиксы проверять как минимум на локалке, а как максимум на стенде перед передачей в тест. Я ещё пробежался поиском по проекту и там не на всех изображениях есть loading=‘lazy’. Подмержи мастер и проверь ещё раз компоненты PictureSmart, и просто img на наличие этого аттрибута.

2020-11-12 14:30 UTC, ArtyomResh commented
Подвинул в RFT, подмержу в мастер, когда Крис аппрувнет

2020-12-02 13:58 UTC, BenuelBertran commented
Проверил на всех страницах корректную передачу значений для PictureSmart и подгрузку изображений на страницах.
Касаемо значений, в коде всё в порядке: loading="lazy" у всех нужных изображений стоит и виден у тега на стенде. 
На странице Projects нижнее изображение футера подгружается корректно. Остальные изображения грузятся сразу, возможно, потому что находятся в "области видимости" вьюпорта фичи loading тега img. (Страница Industries / MVP длиннее проектов, поэтому там в самом низу из четырёх изображений блока два грузятся сразу, а четыре при скролле).

2020-12-03 13:20 UTC, ArtyomResh approved these changes

2020-12-10 13:45 UTC, merged