feat: COM-2824 Jobs page:  change list bullet style
CSSSR/csssr.com pull request #1674
Opened 2020-10-13 10:40 UTC by dyurein

## Задача
- ссылка на jira: COM-2824
- стенд: http://feat-com-2824.com.csssr.cloud/

2020-10-13 14:40 UTC, ArtyomResh requested changes

2020-10-13 14:40 UTC, ArtyomResh commented on components/Layout/Layout.styles.js
> +    top: 0.6rem;
тут должно быть целое число – 0.6 * 16px = 9.6px. Нецелое значение пикселей приводит к непостоянству вёрстки, разные браузеры в разных условиях могут по разному округлять нецелые числа

2020-10-13 15:02 UTC, dyurein commented on components/Layout/Layout.styles.js
> +    top: 0.6rem;
Понял, исправил

2020-10-14 08:43 UTC, ArtyomResh approved these changes

2020-11-10 09:31 UTC, ArtyomResh approved these changes

2020-11-11 12:25 UTC, closed without merging