feat: [COM-2039]: Preset size to first pictures on page
CSSSR/csssr.com pull request #1686
Opened 2020-10-15 12:39 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2039
- стенд: http://feat-com-2039.com.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [+] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [+] Код работает полностью согласно описанию задачи
- [+] eslint и dev-консоль браузера без ошибок

2020-10-16 08:27 UTC, ArtyomResh requested changes
На самом деле этот хак с aspect ratio нам тут не нужен, объясню почему. Этот хак полезен, когда у нас на странице есть респонсив вёрстка, а у нас в адаптив на гридах, но с особенностями. Особенность заключается в том, что на таблетах и мобилках все размеры записываются в ремах, а размер одного рема мы устанавливаем в зависимости от ширины экрана устройства, т.е. мы уже применяем этот хак на этих разрешениях, только не для отдельных элементов, а вообще для всего сайта. [Вот как это выглядит](http://s.csssr.ru/U31J879TR/20201016111256.mp4) – всё пропорционально уменьшается. Поэтому все размеры для таблетов и мобилок важно писать в ремах, для удобства мы сделали функцию которая всё считает за нас – calcRem. 
По-хорошему тут нужно убрать все эти обёртки и формулы, и просто установить изображениям высоту в пикселях и где нужно в ремах, но на задачу и так уже потратили много времени, поэтому просто подтяни себе изменения из мастера, там появились новые страницы, например `/en/projects`. Проверь ещё раз, что бы на всех страницах у изображений был размер. 

Старайся писать идентично, где-то у тебя `padding-top: ${calcRem(248)};`, где-то `padding-top: calc(909 / 1200 * 100%);`, а где-то `padding-top: calc(264 / 318 * ${calcRem(106)});`. Одна и та же запись 3-мя разными способами.

2020-10-16 08:27 UTC, ArtyomResh commented on components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.styles.js
> +    padding-top: calc(1200 / 1200 * 100%);
:)

2020-10-22 10:01 UTC, BenuelBertran commented on components/core-values/DetailValue/DetailValue.styles.js
> +    }
Не для всех (для 4 из 5). Но теперь переделал всё под универсальный размер для блока.

2020-10-22 10:33 UTC, BenuelBertran commented on components/express/Greeting/Greeting.styles.js
> +      padding-top: calc(1776 / 2184 * ${calcRem(728)});
В данном случае это сработает, так как брейкпоинт desktop.l не имеет диапазона, и всё что выше всегда будет равняться указанной высоте. 
Но во всех других случаях придётся оставить формулу расчёта для вывода конкретных значений. Поэтому длинная формула тут скорее для единообразия записи и прозрачности чтения полученного значения.

2020-10-22 11:43 UTC, BenuelBertran commented
> Старайся писать идентично, где-то у тебя `padding-top: ${calcRem(248)};`, где-то `padding-top: calc(909 / 1200 * 100%);`, а где-то `padding-top: calc(264 / 318 * ${calcRem(106)});`. Одна и та же запись 3-мя разными способами.

На самом деле тут три разные записи: если в стилях блока указана конкретная ширина, вроде width: ${calcRem(106)}, то запись будет формата padding-top: calc(264 / 318 * ${calcRem(106)});, если не указана, то padding-top: calc(909 / 1200 * 100%); Запись padding-top: ${calcRem(248)}; используется исключительно в тех случаях, где высота не будет больше меняться (на последнем брейкпоинте), что и рекомендовано в одном из замечаний выше.

2020-10-22 11:43 UTC, BenuelBertran commented on components/jobs/Vacancies/Vacancies.styles.js
> -
Вернул

2020-10-22 11:43 UTC, BenuelBertran commented on components/project/Hero/Hero.styles.js
> +      padding-top: calc(1680 / 1680 * ${calcRem(560)});
Поправил

2020-10-22 11:43 UTC, BenuelBertran commented on components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.styles.js
> +    padding-top: calc(1200 / 1200 * 100%);
Поправил

2020-10-23 07:48 UTC, ArtyomResh commented
> На самом деле тут три разные записи: если в стилях блока указана конкретная ширина, вроде width: ${calcRem(106)}, то запись будет формата padding-top: calc(264 / 318 * ${calcRem(106)});, если не указана, то padding-top: calc(909 / 1200 * 100%); Запись padding-top: ${calcRem(248)}; используется исключительно в тех случаях, где высота не будет больше меняться (на последнем брейкпоинте), что и рекомендовано в одном из замечаний выше.

Ага, мотивы твои понял. 
Но смотри, вне зависимости от контекста проетка `padding-top: calc(264 / 318 * ${calcRem(106)})` это тоже самое что и просто написать `padding-top: ${calcRem(248)}`, потому что в итоге из формулы `264 / 318 * ${calcRem(106)}` мы всегда будем получать одно и тоже значение - `calcRem(88)` и можно было бы сразу просто написать `padding-top: ${calcRem(88)}`. 

Если же в множителе `padding-top: calc(264 / 318 * ${calcRem(106)})` стояло бы 100%, то тогда там могло бы быть и 106 и 206 и на выходе получались бы разные числа. Но из-за того что у нас на проекте адаптив, а не респонсив и большинство изображений стоят по сетке их ширина и высота на конкретном разрешении всегда одинаковые, а между разрешениями у нас зачастую меняются изображения и их пропорции, поэтому вместо `padding-top: calc(909 / 1200 * 100%);` можно спокойно писать просто высоту, потому что по сути за за 100% будет всегда скрываться одно и тоже число. 

Поэтому в будущем для изображений на проекте можешь просто указывать их высоту по макетам, т.к. у нас адаптив, этого будет достаточно для большинства случаев, если появится что-то респонсив, то тогда добавишь формулу.

2020-10-23 07:49 UTC, ArtyomResh approved these changes

2020-11-10 09:34 UTC, merged