COM-2616-e2e-Pojects
CSSSR/csssr.com pull request #1694
Opened 2020-10-20 20:44 UTC by Mikhalenko

## Задача
- ссылка на jira: COM-__2616__

## Дополнительно
Тесты для страниц проектов
* скриншоты
* отправка заявок
* роуты

2020-10-21 07:46 UTC, ArtyomResh commented
@Mikhalenko Тебе нужно настроить [подпись коммитов](https://confluence.csssr.io/pages/viewpage.action?pageId=17631083) и потом сделать то что Саша написал в первом комментарии

2020-10-21 07:47 UTC, ArtyomResh requested changes
Комментарий про подпись выше ^

2020-10-21 15:34 UTC, Mikhalenko commented
@ArtyomResh у меня с первого PR подпись коммитов настроена
и когда я коммитила у меня запрашивало пароль, может что-то у нас поменялось?

2020-10-26 15:41 UTC, ArtyomResh commented
@Mikhalenko у тебя теперь один коммит с подписью, а другой нет, нужно что бы оба были с подписью. Я в другом ПР оставил коммент как решить проблему – https://github.com/CSSSR/csssr.com/pull/1709 (не забудь поменять id коммита)

2020-11-05 13:24 UTC, merged