[COM-2931]: Changed main hero markup and styles
CSSSR/csssr.com pull request #1732
Opened 2020-11-06 15:11 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2931
- стенд: http://com-2931.com.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [x] Указаны ревьюеры
- [x] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-11-09 11:19 UTC, ArtyomResh requested changes

2020-11-09 11:19 UTC, ArtyomResh commented on components/main/Hero/Hero.jsx
> +  <section className={`${className} hero-wrap`}>
Насколько я понял теперь Hero одинаковый и для ru и для en, поэтому нам можно больше не держать два HeroEn и HeroRu и объединить в один. Давай так и сделаем тогда. Изображения тоже вроде одинаковые теперь стали, можно удалить дубликаты

2020-11-09 14:53 UTC, BenuelBertran commented on components/main/Hero/Hero.jsx
> +  <section className={`${className} hero-wrap`}>
Обсуждали это как раз. Изображения и позиционирования отличаются для ru и en версий (хотя и похожи), поэтому пришлось оставить оба варианта стилизации.

2020-11-10 07:48 UTC, ArtyomResh commented on components/main/Hero/Hero.jsx
> +  <section className={`${className} hero-wrap`}>
Да, помню, изображения тогда не трогаем, но надо всё равно убрать разделение на HeroEn и HeroRu в компоненте, у нас теперь одинаковый код разметки для ru и en. Стили тоже надо отрефакторить и вынести всё общее из en и ru, а в en и ru оставить только частные стили

2020-11-10 07:49 UTC, ArtyomResh requested changes
Коммент в треде

2020-11-10 15:16 UTC, ArtyomResh approved these changes
🔥

2020-11-17 10:08 UTC, BenuelBertran commented
Добавил контейнеру обёртке блока Hero такой же размер, как у внутреннего Grid компонента, чтобы картинки на бэкграунде не вылазили за границу при растяжении. 
Заявка на фикс в комментарии к задаче https://jira.csssr.io/browse/COM-2931

2020-11-17 10:16 UTC, ArtyomResh approved these changes

2020-11-18 09:45 UTC, merged