[COM-2498]: Change list bullet styles
CSSSR/csssr.com pull request #1733
Opened 2020-11-06 17:34 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2498
- стенд: http://com-2498.com.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Стенды собрались и работают
- [x] Код работает полностью согласно описанию задачи
- [x] eslint и dev-консоль браузера без ошибок

2020-11-09 08:03 UTC, ArtyomResh requested changes
У тебя стили для буллетов написаны вне медиавыражений, значит они общие для всех разрешений, поэтому нужно писать в ремах, иначе на промежуточных разрешениях между 360 - 767 и 768 - 1024 булеты будет немного съезжать, например, вот что на [500](http://s.csssr.ru/U31J879TR/20201109110125.jpg)

2020-11-09 11:21 UTC, ArtyomResh approved these changes

2020-11-10 12:18 UTC, ArtyomResh commented
Оказывается Сережа уже делал подобное – https://github.com/CSSSR/csssr.com/pull/1674

2020-11-11 12:18 UTC, BenuelBertran commented
В коммите fixup! поправил стили буллетов в соответствии с обновлённой вёрсткой для страницы вакансии.
 
Также, перенёс отличающиеся стили на страницу en/privacy-policy. Теперь все core-стили в компоненте layout (как и должно быть), так что страница вакансии берёт стили оттуда и не требует модификаций.

2020-11-12 14:28 UTC, ArtyomResh commented
Отличный, коммент, спасибо! 👍

2020-11-12 14:28 UTC, ArtyomResh approved these changes

2020-11-17 07:44 UTC, merged