feat: COM-2955 Add discount banner to main page(en)
CSSSR/csssr.com pull request #1764
Opened 2020-11-19 16:01 UTC by dyurein

## Checklist
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2020-11-19 16:05 UTC, dyurein commented on components/main/DiscountBanner/DiscountBanner.jsx
> +        <Global
@ArtyomResh На счет стилей с проверками сомневаюсь. Возможно как-то лучше можно сделать

2020-11-19 18:57 UTC, ArtyomResh requested changes

2020-11-19 18:57 UTC, ArtyomResh commented on static/icons/main/cross.svg
> +</svg>
Я думаю можно использовать какую-либо уже из существующих иконок и не делать новую

2020-11-19 18:57 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.jsx
> +          )}
Кажется это лишнее

2020-11-19 18:57 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.jsx
> +  const [isContactModalVisible, toggleContactModalVisibility] = useState(false)
Кажется это лишнее

2020-11-19 18:57 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.jsx
> +          )}
На созвоне говорили, что клик на мобилке переводит на страницу контактов, а не открывает модалку. Если в процессе работы выяснилось другое, то надо об этом написать в комментарии к задаче

2020-11-19 18:57 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.styles.js
> +    }
На 1920+ и на промежуточных разрешениях между брейкопинтами стрелочка не попадает по кнопке. Её нужно спозиционировать абсолютно и держать всегда на одинаковом расстоянии от правого края

2020-11-19 18:57 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.jsx
> +        <Global
Лучше перенеси это в компонент Hero, потому что тут мы описываем его стили. И там уже смотри, если у Banner есть класс hidden, то у hero-wrap_en будет один оступ, если нет, то другой. И isTablet и isMobile замени на нормальные медиавыражения. А ещё сами стили вынеси в файл стилей и оттуда их импорти для глобал, как мы делаем в других компонентах. Совсем хорошо было бы использовать контекст и держать в нём состояние банера, а в herо получать эту инфу и в зависимости от неё менять инфу, но т.к. у нас не очень много времени, вариант с Global идеально подходит под наши условия.

2020-11-20 07:05 UTC, dyurein commented on components/main/DiscountBanner/DiscountBanner.jsx
> +          )}
Решили открывать модалку. В описании задачи уже указано

2020-11-20 08:44 UTC, dyurein commented on components/main/DiscountBanner/DiscountBanner.styles.js
> +    }
Исправил

2020-11-20 09:06 UTC, dyurein commented on static/icons/main/cross.svg
> +</svg>
Маленьких крестиков не нашел, видимо нужен этот

2020-11-20 09:41 UTC, ArtyomResh commented on static/icons/main/cross.svg
> +</svg>
Ну так ты их уменьшить можешь с помощью css :)

2020-11-20 09:44 UTC, ArtyomResh commented on components/main/DiscountBanner/DiscountBanner.jsx
> +          )}
Не заметил, извини

2020-11-20 09:50 UTC, ArtyomResh requested changes

2020-11-20 09:50 UTC, ArtyomResh commented on components/main/Hero/DiscountBanner/DiscountBanner.styles.js
> +
Перенеси это и Global в Hero. Эти стили меняют Hero поэтому они должны лежать там. Hero идёт по дереву сразу за баннером, можно написать такие селекторы: `.banner + .hero-wrap.hero-wrap_en {...}`, `.banner.is_visible + .hero-wrap.hero-wrap_en {...}`

2020-11-20 11:37 UTC, ArtyomResh approved these changes

2020-11-20 13:47 UTC, ArtyomResh approved these changes

2020-11-20 14:32 UTC, merged