feat: COM-2355 LMS | Add scroll to section start on feature click
CSSSR/csssr.com pull request #1787
Opened 2020-12-01 13:52 UTC by dyurein

## Checklist
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2020-12-02 07:26 UTC, ArtyomResh requested changes
Что-то ничего не изменилось – http://s.csssr.ru/U31J879TR/20201202102457.mp4

2020-12-02 13:43 UTC, dyurein commented
@ArtyomResh Проверил на стенде и на телефоне, у меня нормально срабатывает

2020-12-07 07:59 UTC, ArtyomResh commented
@daynin Я думал задача ещё так же заключается и в том, что бы сама карточка скролилась что бы её видно было на экране – http://s.csssr.ru/U31J879TR/20201207105653.jpg? 

Но если нет, то аппрув

2020-12-07 07:59 UTC, ArtyomResh approved these changes

2020-12-10 13:38 UTC, merged