feat: COM-3017 P4: Updated hero block
CSSSR/csssr.com pull request #1815
Opened 2020-12-23 13:30 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12500
* testing: http://release-com-case-p4.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2020-12-30 15:26 UTC, BenuelBertran requested changes

2020-12-30 15:26 UTC, BenuelBertran commented on components/project/Hero/Hero.styles.js
> +  @keyframes p4-outline {
На 360 и 1024 в русской локализации обводка не доходит до конца слова. Возможно, неверная ширина анимированного блока либо отличающиеся шрифты текста внутри. Нужно проверить

2021-01-11 08:21 UTC, dyurein commented on components/project/Hero/Hero.styles.js
> +  @keyframes p4-outline {
Исправил

2021-01-11 12:32 UTC, ArtyomResh approved these changes

2021-01-11 12:32 UTC, ArtyomResh commented on components/project/GazpromNeftPage.jsx
> -  ]
Надо будет потом, после объединения в одну ветку не забыть удалить всё что нам больше не нужно на этой странице

2021-01-12 07:34 UTC, merged