feat: COM-3028 P4: Added Development block
CSSSR/csssr.com pull request #1819
Opened 2020-12-28 15:22 UTC by dyurein

jira release board: https://jira.csssr.io/projects/COM/versions/12500
testing: http://release-com-case-p4.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2020-12-30 15:13 UTC, BenuelBertran requested changes

2020-12-30 15:13 UTC, BenuelBertran commented on static/locales/ru/project.json
>      "imgAlt": {
Кажется в этом компоненте у тебя совсем не отрабатывает анимация плавного появления features item-ов.
Для того чтобы реализовать такую анимацию тебе нужно настроить зону скролла страницы при попадании в которую должен срабатывать триггер, добавляя класс к блоку с фичами. После чего в стилях станет работать css-transition, который нужно повесить на элементы фичей, чтобы плавно менять значение opacity, как указано в описании компонента в notion. 

Зону скролла тебе поможет отследить IntersectionOberver, который можно подсмотреть в компоненте Observer по пути components/way-of-work/Transparency/Observer

2021-01-11 10:28 UTC, dyurein commented on static/locales/ru/project.json
>      "imgAlt": {
Исправил

2021-01-11 15:12 UTC, ArtyomResh approved these changes

2021-01-12 08:39 UTC, merged