[COM-3024]: Added Challenge section
CSSSR/csssr.com pull request #1822
Opened 2020-12-29 17:17 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12500
* testing: http://release-COM-CASE-P4.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2020-12-30 10:41 UTC, dyurein approved these changes

2021-01-11 14:34 UTC, ArtyomResh requested changes

2021-01-11 14:34 UTC, ArtyomResh commented on components/project/GazpromNeftPage.jsx
> -import { L10nConsumer } from '../../utils/l10nProvider'
Надо будет не забыть удалить всё что стало не нужным после мержа в ветку релиза

2021-01-11 14:34 UTC, ArtyomResh commented on components/project/Challenge/Challenge.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Все обработчики на события по дефолту лучше делать с помощью `addEventListener`, что бы потом их можно было убрать с помощью `removeEventListener`. Если обработчики повешенные на `window` не убирать, то это может привести к багам на других страницах или падению производительности на всём проекте. В твоём случае, после того как пользователь зайдёт на страницу профессионалов, у него потом [на всём проекте будет отрабатывать хендлер, что ты установил для `window.onscroll`](http://s.csssr.ru/U31J879TR/2021-01-11-17-21-29-xppzc.mp4).

2021-01-11 14:34 UTC, ArtyomResh commented on components/project/Challenge/Challenge.jsx
> +  }
Если у тебя какие-то переменные зависят от размеров окна браузера, то скорей всего тебе нужно их положить в хендлер для события `resize` с помощью `addEventListener`, иначе значения этих переменных не будут меняться, если пользователь будет изменять размер окна и [это может сломать твою реализацию](http://s.csssr.ru/U31J879TR/2021-01-11-17-30-40-te3ai.mp4)

2021-01-12 11:12 UTC, merged