feat: COM-3036 Mosoblgaz| Change link
CSSSR/csssr.com pull request #1853
Opened 2021-01-15 10:45 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12704
* testing: http://release-com-project-fix.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-01-18 15:37 UTC, ArtyomResh requested changes

2021-01-18 15:37 UTC, ArtyomResh commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
А зачем пришлось создавать linkTitle? Я вижу что решить проблему можно оставив тут `link(translations)` как было и в файле локалей для en прописать правильный линк из тз

2021-01-19 07:40 UTC, dyurein commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
![image](https://user-images.githubusercontent.com/37905737/105002514-7871d700-5a42-11eb-8d7a-ba4b57bcf3f7.png)
Тайтл и href берутся из одного текста. Тайтл линка стаенет тогда https://mosoblgaz.ru/en. Если это не критично, можно оставить один link
@ArtyomResh

2021-01-20 07:57 UTC, ArtyomResh commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
Мне кажется так будет правильно, но думаю всё же стоит уточнить у Влада или Лёни. Если скажут что нужно что бы было как сделано сейчас у тебя, тогда давай linkTitle заменим на linkText, а сам link на href и сделаем так для всех проектов, что бы везде было идентично

2021-01-20 10:35 UTC, dyurein commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
Сделал ссылку с `en`, linkTitle убрал

2021-01-20 10:35 UTC, dyurein commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
@ArtyomResh

2021-01-21 07:58 UTC, ArtyomResh approved these changes

2021-01-21 07:59 UTC, ArtyomResh commented on components/project/Hero/Hero.jsx
> +            __html: projectId === 'mosoblgaz' ? linkTitle(translations) : link(translations),
Круто! Думаю ещё в комментах к задаче нужно отписаться, что бы Крис было понятней

2021-01-21 08:37 UTC, merged