[COM-3038]: Modified Industries link from Header
CSSSR/csssr.com pull request #1859
Opened 2021-01-18 20:24 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12704

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2021-01-19 07:25 UTC, ArtyomResh requested changes

2021-01-19 07:25 UTC, ArtyomResh commented on components/Header/Menu/Nav/Nav.styles.js
> +        grid-template-columns: 1fr 0.5fr 0.5fr;
Давай ещё и сюда `padding-left: 4%;` перенесём из `tablet.all`, а в `desktop.l`, `desktop.m`, `desktop.s` удалим его и `grid-template-columns` вместе с ним

2021-01-19 07:25 UTC, ArtyomResh commented on components/Header/Menu/Nav/Nav.jsx
> +                            }}
Вынеси `heading` из массива ссылок и тут определяй надо его подставлять или нет по id меню, в файле локалей вынесли `heading` из `mediaAndMarketing` и положи его в просто в `portfolio` под `title`, переименуй в `listTitle`

2021-01-19 07:26 UTC, dyurein approved these changes

2021-01-19 10:36 UTC, ArtyomResh requested changes

2021-01-19 10:36 UTC, ArtyomResh commented on data/headerLinks.js
> +          listTitle: (t) => t.common.header.menu.portfolio.listTitle,
Отсюда listTitle вытащи на 55 строку

2021-01-19 10:36 UTC, ArtyomResh commented on components/Header/Menu/Nav/Nav.jsx
> +                              __html: listTitle(translations),
вот тут подставь translations.common.header.menu.portfolio.listTitle, а из объекта ссылок удали listTitle

2021-01-20 07:41 UTC, ArtyomResh approved these changes

2021-01-20 08:48 UTC, merged