[COM-3091]: Increased quote line size
CSSSR/csssr.com pull request #1883
Opened 2021-01-21 14:12 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12500

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2021-01-22 07:23 UTC, dyurein approved these changes

2021-01-22 07:37 UTC, ArtyomResh requested changes
Тут нужно рефакторнуть компонент. Если в следующих проектах, которые мы будем менять, текст цитаты будет отличаться по количеству символов, то опять придется тут что-то подгонять. Надо сделать высоту `::before` элемента как в 100% `blockquote` + смещение. Бекграунд изображение для цитат придется тоже изменить, думаю проще всего будет разбить его на полоску и треугольник, иначе оно будет непропорционально растягиваться: полоску поставить на репит, а треугольник статично разместить поверх полоски

2021-01-27 13:43 UTC, BenuelBertran commented
Отрефакторил компонент цитаты. По договорённости с ПР, затронуты только изменения аффектящие на страницу Газпрома (в дальнейшем, после переработки других страниц, компонент цитаты будет заменяться на текущий).

Заменил картинки боковой линии для каждого разрешения на стили + svg треугольника.
Поправил изображения, отступы и стили для всех разрешений.

2021-01-27 15:08 UTC, ArtyomResh commented on components/project/Quote/Quote.styles.js
> -const quoteLine = require.context('../../../public/images/project/gazprom-neft/quote/line?csssr-images')
Удали сам файл тоже

2021-01-27 15:21 UTC, ArtyomResh approved these changes
Удали старый файл картинки с линией. Задачу можешь кинуть в RFT, файл этому не мешает. Коммент учти при выполенении вледующих задач

2021-01-27 15:21 UTC, ArtyomResh commented on components/project/Quote/Quote.styles.js
> +      background-position: ${calcRem(180)} ${calcRem(277)}, ${calcRem(1006)} 0, ${calcRem(398)} ${calcRem(763)};
На декстопных разрешениях не обязательно менять пиксели на ремы. Лучше даже не ставить, потому что это потом усложняет дебаг вёрстки из консоли на десктопных разрешениях, приходится переводить ремы обратно в пиксели

2021-01-28 14:36 UTC, merged