[COM-3096]: Modified Gazprom project content data
CSSSR/csssr.com pull request #1897
Opened 2021-01-25 14:05 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12500

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2021-01-26 07:32 UTC, ArtyomResh requested changes

2021-01-26 07:32 UTC, ArtyomResh commented on components/project/Hero/Hero.styles.js
>      }
Можно удалить

2021-01-26 07:32 UTC, ArtyomResh commented on components/project/Hero/Hero.jsx
> +            with_new_padding: language === 'ru',
Это ведь повлекло изменения на всех остальных ру страницах проектов. Добавь `projectId === 'gazpromNeft' && language === 'ru'`. Название класса давай поменяем на `heading_is_wider`

2021-01-27 09:42 UTC, ArtyomResh approved these changes

2021-01-28 07:53 UTC, dyurein approved these changes

2021-01-28 14:59 UTC, merged