[COM-3118]: Implemented active item title to back button link
CSSSR/csssr.com pull request #1907
Opened 2021-01-28 13:57 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12704

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2021-01-29 07:13 UTC, dyurein commented on components/Header/Menu/Nav/Nav.jsx
> +          {activeItem !== null && (
А в каком случае может прийти null?

2021-01-29 07:13 UTC, dyurein approved these changes

2021-02-01 07:35 UTC, ArtyomResh commented on components/Header/Menu/Nav/Nav.jsx
> +          {activeItem !== null && (
Когда, например ты вернулся назад или ещё не выбрал ничего

2021-02-01 08:25 UTC, ArtyomResh requested changes

2021-02-01 08:25 UTC, ArtyomResh commented on components/Header/Menu/Nav/Nav.jsx
> -          {translations.common.header.backLink}
Если нам это больше не нужно то удали эти текста из файла локалей

2021-02-02 08:20 UTC, ArtyomResh approved these changes

2021-02-02 08:55 UTC, merged