[COM-3190] Modified component and styles
CSSSR/csssr.com pull request #1921
Opened 2021-02-09 15:07 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12722
* testing: http://release-com-hireus-bubble.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Browser dev tools has no errors

2021-02-11 08:22 UTC, ArtyomResh requested changes

2021-02-11 08:22 UTC, ArtyomResh commented on components/Layout/Layout.jsx
> +    const target = document.getElementById('site-footer')
Лучше зафоворти ref отсюда в футер или сделай обертку над футером и на неё повесь реф

2021-02-15 16:27 UTC, BenuelBertran commented
Для блока кода, с изменяемыми размерами отступов, в компоненте Layout, заменил текущую реализацию на switch конструкцию. Дополнительный рефакторинг будет выполнен в задаче https://jira.csssr.io/browse/COM-3202

2021-02-16 07:32 UTC, ArtyomResh commented on components/Layout/Layout.jsx
> +      isCookiesPopupVisible && getIdea() && isMobile
@alexbaumgertner Вот это забыл, сделай это тогда тоже в https://jira.csssr.io/browse/COM-3202

2021-02-16 07:32 UTC, ArtyomResh commented on components/Layout/Layout.jsx
> +      isCookiesPopupVisible && getIdea() && isMobile
@BenuelBertran Вот это забыл, сделай это тогда тоже в https://jira.csssr.io/browse/COM-3202

2021-02-16 07:35 UTC, ArtyomResh approved these changes

2021-02-16 07:35 UTC, ArtyomResh commented on components/Bubble/Bubble.styles.js
> +        transform: translate(${bubblePositionMobile});
Раз у тебя теперь в moveOut в 0 стоит такая же позиция, то тут я думаю уже не нужно это писать

2021-02-16 08:05 UTC, merged