COM-3005: E2E test_fixes fallen screen tests Back-end and DevOps EN
CSSSR/csssr.com pull request #1927
Opened 2021-02-16 05:51 UTC by bikmaevakristina

Fixing test:
- Back-end and DevOps 1920 En
- Back-end and DevOps 1360 En
- Back-end and DevOps 1280 En
- Back-end and DevOps 1024 En
- Back-end and DevOps 360 En
- Back-end and DevOps 1024 RU
Remote irrelevant test:
- Rout to Process Page-EN

**Task**
* link JIRA: https://jira.csssr.io/browse/COM-3005
* stand: https://csssr.com/
* run Jenkins: 

**For reviewers**
How to review e2e tests: https://github.com/CSSSR/e2e-tools/blob/master/docs/REVIEW.md

2021-02-16 07:43 UTC, ArtyomResh commented on e2e-tests/nightwatch/tests/05 BackEnd and DevOps/03 Routs.test.js
> -
![](http://s.csssr.ru/U31J879TR/2021-02-16-10-42-16-iv13c_.jpg)
Так вроде есть страница https://csssr.com/en/service/mvp-development и на ней есть ссылка «Read about how we work» на https://csssr.com/en/way-of-work

2021-02-16 12:03 UTC, niktestbom requested changes

2021-02-16 12:03 UTC, niktestbom commented on e2e-tests/nightwatch/tests/05 BackEnd and DevOps/03 Routs.test.js
> -
аналогичный вопрос)

2021-02-16 12:45 UTC, bikmaevakristina commented on e2e-tests/nightwatch/tests/05 BackEnd and DevOps/03 Routs.test.js
> -
да да, я перепутала страницу, исправлю

2021-02-18 13:37 UTC, bikmaevakristina commented on e2e-tests/nightwatch/tests/05 BackEnd and DevOps/03 Routs.test.js
> -
Разобрались, оказалось, что это задублированный файл с другой страницы, удалила этот файл в рамках этой задачи.

2021-02-19 08:19 UTC, ArtyomResh commented
@bikmaevakristina надо ререквестить ревью после правок, а иначе оно не появляется у нас в «Review Requested» и проходит под радаром

2021-02-19 08:21 UTC, ArtyomResh commented on e2e-tests/nightwatch/tests/05 BackEnd and DevOps/03 Routs.test.js
> -
Оставь тут ссылочку на файл дубликат

2021-02-19 08:21 UTC, ArtyomResh approved these changes

2021-02-19 08:21 UTC, ArtyomResh approved these changes

2021-02-19 08:53 UTC, niktestbom approved these changes

2021-02-19 09:30 UTC, merged