feat: SPC-1877 Update candidate form
CSSSR/csssr.com pull request #1937
Opened 2021-02-20 13:52 UTC by dyurein

## Checklist
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-02-24 07:36 UTC, ArtyomResh requested changes
Проверяй что у тебя получается перед передачей задачи в review
![](http://s.csssr.ru/U31J879TR/2021-02-24-10-36-15-147b0_.jpg)

2021-02-24 07:36 UTC, ArtyomResh commented on static/locales/ru/common.json
> +    "conjunction": "или"
Добавленные тексты не относятся к checkBoxesText.
checkBoxesText это тексты для чекбоксов под формами. 
Лучше положи это в form ниже.

2021-02-24 07:36 UTC, ArtyomResh commented on components/job/CandidateInfoSection/CandidateInfoSection.jsx
> +      <p className="conjunction">{translations.common.checkBoxesText.conjunction}</p>
Нужно добавить условие по которому отображается этот текст, ведь если поля для файла нет, то и отображать этот текст не нужно

2021-02-25 07:22 UTC, dyurein commented on static/locales/ru/common.json
> +    "conjunction": "или"
Переместил

2021-02-25 07:40 UTC, dyurein commented on components/job/CandidateInfoSection/CandidateInfoSection.jsx
> +      <p className="conjunction">{translations.common.checkBoxesText.conjunction}</p>
Добавил

2021-02-25 09:01 UTC, dyurein commented
> Проверяй что у тебя получается перед передачей задачи в review
> ![](https://camo.githubusercontent.com/525741eb7006fc0ca425bc78faf421ecfd354492c49c58108abb45f712c7f80b/687474703a2f2f732e63737373722e72752f5533314a38373954522f323032312d30322d32342d31302d33362d31352d31343762305f2e6a7067)

Не знал, что есть такая тестовая статья :)

2021-03-01 08:26 UTC, ArtyomResh approved these changes

2021-06-16 13:22 UTC, closed without merging

2021-06-16 13:22 UTC, vkosinov commented
https://github.com/CSSSR/csssr.com/pull/2101 - актуальный