[COM-3184]: Added Tags component
CSSSR/csssr.com pull request #1938
Opened 2021-02-24 09:27 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12730
* testing: http://release-com-modalka.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Browser dev tools has no errors

2021-02-25 08:07 UTC, ArtyomResh requested changes

2021-02-25 08:07 UTC, ArtyomResh commented on components/ContactModal/ContactModal.jsx
> +          <OutsideClickHandler onOutsideClick={(e) => this.outsideClickHandler(e)}>
```suggestion
          <OutsideClickHandler onOutsideClick={this.outsideClickHandler}>
```

2021-02-25 08:07 UTC, ArtyomResh commented on components/ContactModal/ContactModal.styles.js
> +  ${base(props)}
```suggestion
  ${base()}
```

2021-02-25 08:07 UTC, ArtyomResh commented on static/icons/closeCross.svg
> +</svg>
У нас на проекте уже есть какие-то cross иконки, среди них нет подходящих?

2021-02-25 09:51 UTC, ArtyomResh commented on components/ContactModal/ContactModal.styles.js
> +    padding: 64px 40px 40px 40px;
Тут padding надо в ремах

2021-02-25 09:51 UTC, ArtyomResh commented on static/icons/closeCross.svg
> +</svg>
@BenuelBertran ответь мне, пожалуйста, что-нибудь)

2021-02-25 09:51 UTC, ArtyomResh requested changes

2021-02-25 09:51 UTC, ArtyomResh commented on components/ContactModal/ContactModal.styles.js
> +    padding: 64px 40px 40px 40px;
Тут padding надо в ремах

2021-02-25 12:36 UTC, BenuelBertran commented on static/icons/closeCross.svg
> +</svg>
Удалена иконка closeCross. Взята иконка с крестом из иконок на проекте.

2021-02-25 12:42 UTC, BenuelBertran commented on components/ContactModal/ContactModal.styles.js
> +    padding: 64px 40px 40px 40px;
Стили блоков модалки изменены в задаче по вёрстке https://github.com/CSSSR/csssr.com/pull/1938.
Но добавил и тут в коммите ниже.

2021-02-26 10:13 UTC, ArtyomResh approved these changes

2021-02-26 11:03 UTC, merged