feat(submit-form) Reread auto rotating google service account keys
CSSSR/csssr.com pull request #1979
Opened 2021-03-15 08:42 UTC by qtm

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* testing: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors 

## Optional (if you have something to add, otherwise this heading and the paragraph below can be removed)
* comments to the problem solving
* documentation on added libraries
* screenshots

2021-03-18 06:46 UTC, ArtyomResh requested changes

2021-03-18 06:46 UTC, ArtyomResh commented on server/submit-form.js
> +        const analyticsreportingResponse = await backOff(() => userActivitySearch(), backOffOpts)
```suggestion
        const analyticsreportingResponse = await backOff(userActivitySearch, backOffOpts)
```

2021-03-18 06:46 UTC, ArtyomResh approved these changes

2021-05-06 14:28 UTC, ArtyomResh commented
Задача в Jira: COM-3363

2021-05-07 09:35 UTC, Nitive approved these changes

2021-05-07 09:35 UTC, Nitive commented on server/submit-form.js
> +      console.error(`server/submit-form.js ERROR | Reload vault key attempt: ${attemptNumber}`, err)
[note] лучше JSON логировать, по нему легче графики/алерты настроить, если понадобится

2021-05-18 10:39 UTC, merged