feat(header): COM-2965 Add Header from core-design
CSSSR/csssr.com pull request #2000
Opened 2021-04-08 11:18 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-04-08 11:19 UTC, vkosinov commented on data/headerLinks.js
> +  menu[0].links.push({
В этом месте не уверен возможно можно было сделать как то более изящно

2021-04-09 07:58 UTC, ArtyomResh requested changes

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
> +        href: `${language}/service/outsourcing-front-end`,
когда пишешь такой хрев, то заменяться только путь после последнего слеша. Т.e. если ты будешь на странице `https://feat-com-2965.com.csssr.cloud/ru/service/outsourcing-front-end`, то если нажмёшь на «Наши проекты» попадёшь на `https://feat-com-2965.com.csssr.cloud/ru/service/ru/projects`. Попробуй поставить слеш в начале href или заменить на полный путь

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
> +const menuShort = (t, language = 'ru') => [
Мне кажется будет лучше назвать `menuCommon`

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
> +const menuLong = (t, language = 'en') => {
А это тогда будет menuEn

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
> +const menuLong = (t, language = 'en') => {
У тебя menuLong всегда будет только на английском языке, поэтому ты можешь избавится от language аттрибута

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
>      // },
Думаю что можем это совсем удалить)

2021-04-09 07:58 UTC, ArtyomResh commented on data/headerLinks.js
> +  menu[0].links.push({
Да в целом и так хорошо)

2021-04-13 06:38 UTC, ArtyomResh approved these changes

2021-04-15 07:28 UTC, ArtyomResh approved these changes

2021-04-15 12:10 UTC, merged