fix: COM-3459 Сleaning the form in contacts
CSSSR/csssr.com pull request #2040
Opened 2021-05-07 07:50 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-05-07 14:46 UTC, ArtyomResh approved these changes

2021-05-11 07:43 UTC, maksim-kononov-csssr commented on components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.jsx
> +
В этом файле выше уже есть reset() в обработчике handleSubmit - получается он не работает? Если да, то почему? Я бы разобрался и сделал reset формы в одном месте 
https://github.com/CSSSR/csssr.com/blob/6ae24d688455fcda795161323289cf7e9ed9b00a/components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.jsx#L81

2021-05-24 07:42 UTC, ArtyomResh requested changes

2021-05-24 07:42 UTC, ArtyomResh commented on components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.jsx
> +        reset()
А при неудачной отправке ведь тоже будет резетится? Если да, то мы этого не хотим, потому что если отправка не удалась, мы не хотим стирать данные форме, что бы пользователь легко мог её повторить

2021-05-25 15:03 UTC, vkosinov commented
https://github.com/final-form/final-form-focus/issues/14 - есть не решенная проблема с авто фокусом на первый не валидный field

2021-05-26 07:09 UTC, ArtyomResh approved these changes

2021-05-26 10:12 UTC, merged