fix: COM-3530 Fix header links jobs locale
CSSSR/csssr.com pull request #2062
Opened 2021-05-21 12:22 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-05-24 07:36 UTC, ArtyomResh requested changes

2021-05-24 07:36 UTC, ArtyomResh commented on data/headerLinks.js
> +      href: `/${language === 'ru' ? 'ru-ru' : 'en-sg'}/jobs`,
У нас ещё есть en-us, en-ee их тут тоже нужно учитывать

2021-05-24 07:41 UTC, vkosinov commented on data/headerLinks.js
> +      href: `/${language === 'ru' ? 'ru-ru' : 'en-sg'}/jobs`,
А страницы для них разве есть сейчас?

2021-05-25 12:15 UTC, ArtyomResh approved these changes

2021-05-26 10:12 UTC, merged