fix: COM-2896 Fix sending dataLayer event
CSSSR/csssr.com pull request #2071
Opened 2021-05-26 13:00 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors

2021-05-27 07:21 UTC, ArtyomResh requested changes

2021-05-27 07:21 UTC, ArtyomResh commented on server/submit-form.js
> +import { testEmails } from '../utils/testEmails'
Вот тут у тебя неправильно будет. Для почты no+notifications не будет проставляться тестовый тег при отправки в АМО. Тут нет никаких dataLayer отправок, потому что это сервер, а на сервере нет window объекта, поэтому тут надо просто оставить как было.

2021-05-27 07:25 UTC, vkosinov commented on server/submit-form.js
> +import { testEmails } from '../utils/testEmails'
```js
export const testEmails = [testEmail, testEmailNoNotification]
```

это разве не так как было ?

2021-05-28 07:40 UTC, ArtyomResh approved these changes

2021-05-31 09:46 UTC, maksim-kononov-csssr commented on server/submit-form.js
> +import { testEmails } from '../utils/testEmails'
Поддерживаю - нужно сделать нейминг более очевидным. Когда я до этого в коде видел `test+no+notification@csssr.io` - совсем не очевидно что это значит, какие оповещения имеются ввиду, и сейчас еще добавятся новые сущности со со словом test, станет еще запутанней. Мне очень понравилась табличка из описания в задаче что сделала Кристина https://jira.csssr.io/browse/COM-2896 - я бы добавил ее в файл utils/testEmails.js, и в идеале всю логику с почтой можно закрыть в нем, чтобы не писать в разных местах логику вроде `const isTestEmail = testEmailDefault === values.email`

2021-06-01 10:03 UTC, ArtyomResh commented on server/submit-form.js
> +import { testEmails } from '../utils/testEmails'
Заведу задачу в беклог

2021-06-01 10:03 UTC, merged