fix(request): COM-3279 log vacancy request
CSSSR/csssr.com pull request #2078
Opened 2021-05-28 11:26 UTC by ArtyomResh

2021-05-31 07:59 UTC, vkosinov requested changes

2021-05-31 07:59 UTC, vkosinov commented on components/job/JobPage.jsx
> +    console.log(
Наверное забыл убрать ?)

2021-05-31 09:05 UTC, maksim-kononov-csssr commented on .env.development
> +CSSSR_SPACE_ORIGIN=http://localhost:3030
При запуске я всегда использую CSSSR_SPACE_ORIGIN=http://master.space.csssr.cloud - это правильно? И получается это все равно перебивает настройку в этом файле

2021-05-31 09:05 UTC, maksim-kononov-csssr commented on components/job/JobPage.jsx
> +      `/api/public/vacancies/${query.preview ? 'preview' : 'active'}?locale=${locale}`,
Мне кажется или тут ничего не изменилось? Только выравнивание

2021-05-31 09:06 UTC, maksim-kononov-csssr commented on components/job/JobPage.jsx
> +    console.log(
Название PR log vacancy request 🤔🤔🤔

2021-06-01 10:13 UTC, ArtyomResh commented
Не обращайте внимания, этот PR мне нужен был только что бы поднять стенд с нужным CSSSR_SPACE_ORIGIN

2021-06-01 10:13 UTC, ArtyomResh commented
Я его закрою потом

2021-06-01 13:06 UTC, closed without merging