Feat/com 3622
CSSSR/csssr.com pull request #2087
Opened 2021-06-03 16:25 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors

2021-06-07 07:45 UTC, ArtyomResh reviewed
![Скриншот с количеством изменённых файлов](http://s.csssr.ru/U31J879TR/2021-06-07-10-44-29-d57fr_.png) 
T__________T

2021-06-07 09:58 UTC, ArtyomResh requested changes

2021-06-07 09:58 UTC, ArtyomResh commented on common/getPagePathnameInLanguage.js
> +  const pathname = path.replace(/^\/(?<levelOne>.*?)(?<levelTwo>\/(?<subLevelTwo>.*))?$/, '$3')
Давай вот такие штуки писать более явно: 
```suggestion
  const regexp = /^\/(?<levelOne>.*?)(?<levelTwo>\/(?<subLevelTwo>.*))?$/
  const pathname = regexp.exec(path).groups.subLevelTwo
```

2021-06-07 09:58 UTC, ArtyomResh commented on common/getPagePathnameInLanguage.js
> +  const pathname = path.replace(/^\/(?<levelOne>.*?)(?<levelTwo>\/(?<subLevelTwo>.*))?$/, '$3')
Проверь другие regexp

2021-06-07 09:58 UTC, ArtyomResh commented on .prettierrc.js
> +}
Кажется у меня теперь дефолтные настройки `eslint(prettier/prettier)` [перетирают](http://s.csssr.ru/U31J879TR/2021-06-07-12-38-47-1gf5g_.png) настройки указанные в `.prettierrc.js`, как ты с этим поборолся?

2021-06-07 09:58 UTC, ArtyomResh commented on components/ContactModal/ContactModal.jsx
> +        role="dialog"
А тут точно надо отключать это правило eslint если ты поставил роль?

2021-06-07 09:58 UTC, ArtyomResh commented on components/contact-us/ContactUs/Map/Address/Address.jsx
> +            key={addressId}
а тут на что жаловался линтер?

2021-06-07 09:58 UTC, ArtyomResh commented on .eslintrc.js
> +    'no-nested-ternary': 'off',
оставь коммент почему ты это отключил

2021-06-07 09:58 UTC, ArtyomResh commented on components/job/section-types/QuestBox/QuestBox.jsx
> +      // Нет возможности выбрать другой key так-как данные приходят с сервер в массиве
c серверА

2021-06-07 13:27 UTC, vkosinov commented on common/getPagePathnameInLanguage.js
> +  const pathname = path.replace(/^\/(?<levelOne>.*?)(?<levelTwo>\/(?<subLevelTwo>.*))?$/, '$3')
попробуй удалить  `node_modules` и переустановить пакеты

2021-06-07 13:28 UTC, vkosinov commented on .prettierrc.js
> +}
попробуй удалить  `node_modules` и переустановить пакеты

2021-06-07 13:43 UTC, vkosinov commented on components/ContactModal/ContactModal.jsx
> +        role="dialog"
`role="dialog"` не решает проблему которая отключена линтером

2021-06-07 13:44 UTC, vkosinov commented on components/contact-us/ContactUs/Map/Address/Address.jsx
> +            key={addressId}
```
'id' is already declared in the upper scope on line 14 column 18
```

2021-06-07 14:04 UTC, vkosinov commented on .eslintrc.js
> +    'no-nested-ternary': 'off',
удалил отключение правила, пофиксил несоответствия

2021-06-07 15:29 UTC, ArtyomResh approved these changes

2021-06-07 15:31 UTC, ArtyomResh requested changes

2021-06-07 15:31 UTC, ArtyomResh commented on utils/isInvalidBrowser.js
> +    )
Вот тут regexp ещё обнови

2021-06-09 07:17 UTC, ArtyomResh approved these changes

2021-06-16 14:12 UTC, merged