[COM-3625]: update pull request template and CODEOWNERS
CSSSR/csssr.com pull request #2088
Opened 2021-06-04 11:40 UTC by maksim-kononov-csssr

Jira issue: https://jira.csssr.io/browse/COM-3625

- [] PR: name meets the requirements
- [] PR: assignee is assigned
- [] PR: directed to the correct branch
- [] PR: diff is verified, nothing superfluous
- [] Tests: new functionality and fixed bugs covered by tests
- [] Docs: new modules, implementation of the new API, new configs (environment variables), important agreements, and architectural decisions are documented

Useful links:

[Commits and PRs requirements](docs/COMMITS_AND_PRS_REQUIREMENTS.md)

[How to review e2e-tests](https://github.com/CSSSR/e2e-tools/blob/master/docs/REVIEW.md)

[Recommended format for testId names](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md)

2021-06-04 11:51 UTC, maksim-kononov-csssr commented
Дополнительно я добавил себя и Виктора в CODEOWNERS для того чтобы мы автоматически назначались на review

2021-06-04 15:41 UTC, vkosinov reviewed
Оформление коммитов и PR-ов  не стоит сделать еще и en версию?

2021-06-04 15:41 UTC, vkosinov commented on docs/COMMITS_AND_PRS_REQUIREMENTS.md
> + - Пример: `TRIVIAL: Fix typo in README file`
Почему `TRIVIAL` - заглавными а  `Release` нет ?

2021-06-07 07:37 UTC, maksim-kononov-csssr commented on docs/COMMITS_AND_PRS_REQUIREMENTS.md
> + - Пример: `TRIVIAL: Fix typo in README file`
Это соглашение по именованию как название констант - заглавными буквами

2021-06-07 07:40 UTC, maksim-kononov-csssr commented
> Оформление коммитов и PR-ов не стоит сделать еще и en версию?

Поддерживать две версии документа кажется излишним. Я думаю, что вообще лучше в wiki перебросить этот файл, сразу об этом не подумал

2021-06-07 07:42 UTC, ArtyomResh requested changes

2021-06-07 07:42 UTC, ArtyomResh commented on docs/COMMITS_AND_PRS_REQUIREMENTS.md
> + - Пример: `TRIVIAL: Fix typo in README file`
Согласен, я бы привёл к одному виду, либо `Release` капсом, либо `TRIVIAL` с прописной

2021-06-07 07:42 UTC, ArtyomResh commented on .github/pull_request_template.md
> +[Recommended format for testId names](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md)
Давай тут список сделаем

2021-06-07 07:42 UTC, ArtyomResh commented on .github/pull_request_template.md
> -* jira release board: https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
Вот тут я пока не уверен что это стоит убирать, но давай пока попробуем без этого

2021-06-07 07:43 UTC, ArtyomResh requested changes

2021-06-07 07:43 UTC, ArtyomResh commented on .github/pull_request_template.md
> +Jira issue: https://jira.csssr.io/browse/__JIRA_ID__
Тут можно не указывать всю ссылку, а оставить только *COM-__JIRA_ID__*, у нас в репе работает автоподстановка для ссылок из jira

2021-06-07 11:46 UTC, maksim-kononov-csssr commented on docs/COMMITS_AND_PRS_REQUIREMENTS.md
> + - Пример: `TRIVIAL: Fix typo in README file`
Привел к одному виду, оба с прописной, а дальше строчными

2021-06-07 11:48 UTC, maksim-kononov-csssr commented on .github/pull_request_template.md
> +[Recommended format for testId names](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md)
Сделал списком

2021-06-07 11:57 UTC, maksim-kononov-csssr commented on .github/pull_request_template.md
> +Jira issue: https://jira.csssr.io/browse/__JIRA_ID__
Исправил

2021-06-07 15:26 UTC, ArtyomResh approved these changes

2021-06-17 14:23 UTC, merged