COM-3629: E2E test_fixes screenshot tests page MVP
CSSSR/csssr.com pull request #2095
Opened 2021-06-10 10:54 UTC by bikmaevakristina

Fixing test:

**Task**
* link JIRA: https://jira.csssr.io/browse/COM-3629
* stand: https://csssr.com/
* run Jenkins: chrome https://jenkins.csssr.ru/job/csssr-com-nightwatch-e2e/job/COM-3629/7
ff https://jenkins.csssr.ru/job/csssr-com-nightwatch-e2e/job/COM-3629/4

**For reviewers**
How to review e2e tests: https://github.com/CSSSR/e2e-tools/blob/master/docs/REVIEW.md

2021-06-11 10:14 UTC, maksim-kononov-csssr approved these changes

2021-06-15 11:15 UTC, ArtyomResh requested changes

2021-06-15 11:15 UTC, ArtyomResh commented on e2e-tests/nightwatch/tests/Screenshots 02 MVP.test.js
> +        return document.querySelector('[data-testid="projects:block.bubbleButton"]').style = "display: none;"
У тебя так часто повторяется этот селектор и сама функция по его сокрытию, что я бы на твоём месте вынес этот селектор `[data-testid="projects:block.bubbleButton"]` в general и написал отдельную функцию, которая его скрывала и переиспользовал бы её тут

2021-06-16 14:14 UTC, bikmaevakristina commented on e2e-tests/nightwatch/tests/Screenshots 02 MVP.test.js
> +        return document.querySelector('[data-testid="projects:block.bubbleButton"]').style = "display: none;"
Готово, вынесла

2021-06-17 07:40 UTC, ArtyomResh commented on e2e-tests/nightwatch/tests/Screenshots 02 MVP.test.js
> +        return document.querySelector('[data-testid="projects:block.bubbleButton"]').style = "display: none;"
Красота, и кода меньше и работать с этим потом будет проще

2021-06-17 07:40 UTC, ArtyomResh approved these changes

2021-06-17 08:21 UTC, niktestbom approved these changes

2021-06-18 08:40 UTC, merged