COM-3665: E2E test_add screenshot tests page DesignLab
CSSSR/csssr.com pull request #2097
Opened 2021-06-11 10:35 UTC by bikmaevakristina

Add test:
- Rout to Web Development Outsourcing EN
- DesignLab 1920 En
- DesignLab 1360 En
- DesignLab 1280 En
- DesignLab 1024 En
- DesignLab 360 En

**Task**
* link JIRA: https://jira.csssr.io/browse/COM-3665
* stand: https://csssr.com/en
* run Jenkins: chrome https://jenkins.csssr.ru/job/csssr-com-nightwatch-e2e/job/COM-3665/5/
 ff https://jenkins.csssr.ru/job/csssr-com-nightwatch-e2e/job/COM-3665/4

**For reviewers**
How to review e2e tests: https://github.com/CSSSR/e2e-tools/blob/master/docs/REVIEW.md

2021-06-15 11:26 UTC, ArtyomResh requested changes

2021-06-15 11:26 UTC, ArtyomResh commented on components/design/DesignCases/Case/Case.jsx
> +        data-testid={`DesignCases:block:case.${id(translations)}.image`}
Лучше заменить название id:
```suggestion
        data-testid={`DesignCases:block:case.${id(translations)}.imageWrapper`}
```
Одну и туже вещь лучше всегда называть одинаково, что бы проще было находить общий язык и понимать код

2021-06-15 11:26 UTC, ArtyomResh commented on e2e-tests/nightwatch/tests/pageObject/designLab.js
> +const { design } = require("../data/pages")
Я бы сам фолдер `pageObject` переименовал бы в `selectors`. Это более конкретней и лучше описывает то что у вас лежит в этих файлах, а лежат у вас в них объекты с селекторами, как общие, так и для конкретных страниц

2021-06-15 11:26 UTC, ArtyomResh commented on static/locales/en/design.json
> +    "text": "You can read about our core mission, i.e. making complex websites & web applications, on the <a href='outsourcing-front-end' class='devBlock__link' data-testid='DesignCases:dev.link'>rel
Согласно этой [доке](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md), сначала ты указываешь тип, а потом через двоеточие уточняю инфу, т.ё у тебя должно быть вот так: 
```suggestion
    "text": "You can read about our core mission, i.e. making complex websites & web applications, on the <a href='outsourcing-front-end' class='devBlock__link' data-testid='DesignCases:link:dev'>relevant page</a>."
```

2021-06-16 06:23 UTC, bikmaevakristina commented on components/design/DesignCases/Case/Case.jsx
> +        data-testid={`DesignCases:block:case.${id(translations)}.image`}
Названием data-testid занимаются разработчики, по этому я не могу их поправить.
И ПР по ним ранее был от тебя уже апрувнут.

2021-06-16 06:24 UTC, bikmaevakristina commented on static/locales/en/design.json
> +    "text": "You can read about our core mission, i.e. making complex websites & web applications, on the <a href='outsourcing-front-end' class='devBlock__link' data-testid='DesignCases:dev.link'>rel
Названием data-testid занимаются разработчики, по этому я не могу их поправить.

2021-06-16 09:25 UTC, bikmaevakristina commented on e2e-tests/nightwatch/tests/pageObject/designLab.js
> +const { design } = require("../data/pages")
Исправила отдельным коммитом.

2021-06-16 13:41 UTC, ArtyomResh commented
@bikmaevakristina попроси @vkosinov поправить data-testid

2021-06-16 14:20 UTC, vkosinov commented on static/locales/en/design.json
> +    "text": "You can read about our core mission, i.e. making complex websites & web applications, on the <a href='outsourcing-front-end' class='devBlock__link' data-testid='DesignCases:dev.link'>rel
>${Контекст}:${тип}:${опциональная уточняющая информация через точку}

`опциональная уточняющая информация через точку` - dev.link не правильно понимаю ?

2021-06-16 14:43 UTC, ArtyomResh commented on static/locales/en/design.json
> +    "text": "You can read about our core mission, i.e. making complex websites & web applications, on the <a href='outsourcing-front-end' class='devBlock__link' data-testid='DesignCases:dev.link'>rel
@vkosinov да, верно, но там же в доке написано, что link это тип

2021-06-17 07:44 UTC, ArtyomResh approved these changes

2021-06-18 08:22 UTC, merged