COM-3217: Move files from static to public folder
CSSSR/csssr.com pull request #2118
Opened 2021-06-24 12:18 UTC by vkosinov

Jira issue: COM-3217

Checklist:

- [x] PR: name meets the requirements
- [x] PR: assignee is assigned
- [x] PR: directed to the correct branch
- [x] PR: diff is verified, nothing superfluous
- [x] Tests: new functionality and fixed bugs covered by tests
- [ ] Docs: new modules, implementation of the new API, new configs (environment variables), important agreements, and architectural decisions are documented

2021-06-28 07:47 UTC, ArtyomResh requested changes

2021-06-28 07:47 UTC, ArtyomResh commented on components/Bubble/Bubble.styles.js
> +          background-image: url('/icons/projects/triangle_red.svg');
Когда мы подставляем svg изображения c `require`, то они проходят через обработку в webpack. Там у нас настроены лоудеры, которые ужимают svg изображения + webpack собирает бандлы только с нужными изображениями.

Почему понадобилось убрать `require`?

2021-06-28 07:53 UTC, vkosinov commented on components/Bubble/Bubble.styles.js
> +          background-image: url('/icons/projects/triangle_red.svg');
А для чего мы переносим статику в `public`, а не оставляем ее в `static` в таком случае?
Если убрать `require` он просто получит ее по пути `/icons/projects/triangle_red.svg`, если мы хотим обрабатывать svg то может оставим перенос на этапе сборки и оставим папку `static` для svg?

2021-06-30 07:23 UTC, ArtyomResh commented on components/Bubble/Bubble.styles.js
> +          background-image: url('/icons/projects/triangle_red.svg');
Что бы:
1. файлы статики лежали в одном месте
2. разтришейкать общий, самый большой бандл http://s.csssr.ru/U31J879TR/2021-06-30-10-21-55-u2sl1_.png

2021-06-30 07:23 UTC, ArtyomResh commented on components/Bubble/Bubble.styles.js
> +          background-image: url('/icons/projects/triangle_red.svg');
В отпуске надо отдыхать, а не отвечать на комменты к PR)

2021-06-30 09:59 UTC, ArtyomResh commented
Я решил что лучше оставить их как есть, потому что svg вообще не должны попадать в бандл и когда мы их просто загружаем по ссылке, то это хорошо. Сами прогнал через svgo. Автоматизировать это не стал, потому что проект замораживается.

2021-07-02 07:50 UTC, maksim-kononov-csssr approved these changes

2021-07-06 10:28 UTC, ArtyomResh approved these changes

2021-07-12 15:41 UTC, merged