COM-3742: E2E тесты_обновление только логики (без скринов)
CSSSR/csssr.com pull request #2157
Opened 2021-11-15 17:32 UTC by anurgalieva

Jira issue: COM-3742

Скрины необходимо обновить аккурат к релизу) сейчас проверка только логики с небольшим количеством скринов. 
Стенд: https://release-21-44.com.csssr.cloud/

2021-11-16 12:59 UTC, niktestbom commented
Думаю лучше объединить коммиты в один общий.  Плюс в название коммита добавить номер задачи. И если не ошибаюсь - на этом проекте их по английский называют.

2021-11-16 13:05 UTC, niktestbom commented
На скрине e2e-tests/nightwatch/screenshots/base/Screenshots_02_MVP/MVP-off_1024_EN/chrome-1024x6700.png появилась оранжевая плашка вверху, её до этого точно специально не скрывали?

2021-11-16 13:34 UTC, niktestbom requested changes

2021-11-16 13:34 UTC, niktestbom commented on e2e-tests/nightwatch/tests/03 Main.test.js
> +// })
ок, что закомментировано ? а то пометки нет

2021-11-16 13:34 UTC, niktestbom commented on e2e-tests/nightwatch/tests/03 Main.test.js
> +// })
Тоже - ок что закомментировано?

2021-11-16 13:34 UTC, niktestbom commented on e2e-tests/nightwatch/tests/03 Vacancies.test.js
> +          }
мне кажется стоило добавить сразу на все форматы условие

2021-11-16 13:34 UTC, niktestbom commented on e2e-tests/nightwatch/tests/05 FAQ.test.js
>    })
А ок что теперь кидает просто на главную?

2021-11-16 13:34 UTC, niktestbom commented on e2e-tests/nightwatch/tests/09 Redirects.test.js
> +      //browser.assert.urlEquals(`${pages.com.url}${pages.enLocal.url}${pages.outsourcingFrontEnd.url}`)
можно убрать наверное эту строчку тогда

2021-11-16 14:49 UTC, anurgalieva commented on e2e-tests/nightwatch/tests/03 Vacancies.test.js
> +          }
не понимаю(

2021-11-16 14:51 UTC, anurgalieva commented on e2e-tests/nightwatch/tests/05 FAQ.test.js
>    })
Там проблема в том, что в env был указан прод, поэтому проверка проходила. Если указать тестовый стенд - проверка валится, если в pages поменять, допустим, WWW.тестовый стенд - то такое тоже не сработает, потому что на тестовых стнедах не настроен редирект со всяких таких штук. То есть сейчас по хожу проверок на тестовм стенде проверяется еще и прод. Но решила оставить все равно проверки, так как все равно потом на прод будем переориентировать тесты.

2021-11-16 14:55 UTC, anurgalieva commented on e2e-tests/nightwatch/tests/03 Main.test.js
> +// })
ля... я похоже торопилась и забыла раскомментировать этот кусок. Сейчас тесты прогнала - норм работают.

2021-11-16 14:55 UTC, anurgalieva commented on e2e-tests/nightwatch/tests/03 Main.test.js
> +// })
запушила

2021-11-17 06:54 UTC, anurgalieva commented
> На скрине e2e-tests/nightwatch/screenshots/base/Screenshots_02_MVP/MVP-off_1024_EN/chrome-1024x6700.png появилась оранжевая плашка вверху, её до этого точно специально не скрывали?

2021-11-17 06:54 UTC, closed without merging